homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 51.5388
  longitude: -0.1520
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 30
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London


# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  platform: yr

# Text to speech
tts:
  platform: google

media_player livingRoom:
  - platform: kodi
    host: 192.168.0.4
    port: 18080
    username: kodi
    password: arse

media_player cast:
  - platform: cast

light:
  platform: limitlessled
  bridges:
    - host: 192.168.0.16
      groups:
      - number: 1
        name: Bed Room
        type: rgbw
      - number: 2
        type: rgbw
        name: Living Room 1
      - number: 3
        type: rgbw
        name: Living Room 2
      - number: 4
        type: rgbw 
        name: 4


emulated_hue:

switch:
  - platform: broadlink
    host: 192.168.0.3
    mac: '34:ea:34:e7:f9:68'
    timeout: 15
    switches:
      # Will work on most Phillips TVs:
      tv_living:
        friendly_name: "28"
        command_on: 'JgBkAnM4EA0QKRANEAwRDBANEAwRDBANEAwRDBANEA0QKRANEAwRDBANEAwRDBANEAwRDBAqEAwQ
        DRANEAwRDBANEAwRDBApEQwQKREMEA0QDRAMEA0QKREMECkRDBANEAwRDBAqEAAJoHQ3EQwQKhAM
        EA0QDRAMEQwQDRAMEQwQDRAMEQwQKhAMEA0QDRAMEQwQDRAMEQwQDRApEA0QDBEMEA0QDRAMEA0Q
        DRApEA0QKRANEAwRDBANEAwRKRANECkQDRAMEQwQDRApEAAJoXQ4EA0QKRANEAwRDBANEAwRDBAN
        EAwRDBANEAwRKRANEAwQDRANEAwRDBANEAwRDBApEQwQDRANEAwQDRANEAwRDBApEQwQKREMEA0Q
        DBEMEA0QKREMECkRDBANEAwRDBApEQAJoXQ3EA0QKREMEA0QDBEMEA0QDBEMEA0QDBEMEA0QKRAN
        EA0QDBEMEA0QDBEMEA0QDBEpEAwRDBANEA0QDBEMEA0QDBEpEAwRKRAMEQwQDRANEAwQKhAMESkQ
        DBEMEA0QDBEpEAAJoHQ4EAwRKRANEAwQDRANEAwRDBANEAwRDBANEAwRKRAMEQwQDRANEAwRDBAN
        EAwRDBApEQwQDRAMEQwQDRANEAwQDRApEQwQKREMEA0QDBEMEA0QKRANECkQDRANEAwRDBApEQAJ
        oXQ3EA0QKRAODw0QDBEMEA0QDBEMEA0QDBEMEA0QKRANEA0QDBANEA0QDBEMEA0QDBEoEQwRDBAN
        EA0QDBANEA0QDBEpEAwRKRAMEQwQDRAMEQwQKhAMESkQDBEMEA0QDBEpEAANBREMEA0mAGQCczgQ
        DRApEA0QDBEMEA0QDBEMEA0QDBEMEA0QDRApEA0QDBEMEA0QDBEMEA0QDBEMECoQDBANEA0QDBEM
        EA0QDBEMECkRDBApEQwQDRANEAwQDRApEQwQKREMEA0QDBEMECoQAAmgdDcRDBAqEAwQDRANEAwR
        DBANEAwRDBANEAwRDBAqEAwQDRANEAwRDBANEAwRDBANECkQDRAMEQwQDRANEAwQDRANECkQDRAp
        EA0QDBEMEA0QDBEpEA0QKRANEAwRDBANECkQAAmhdDgQDRApEA0QDBEMEA0QDBEMEA0QDBEMEA0Q
        DBEpEA0QDBANEA0QDBEMEA0QDBEMECkRDBANEA0QDBANEA0QDBEMECkRDBApEQwQDRAMEQwQDRAp
        EQwQKREMEA0QDBEMECkRAAmhdDcQDRApEQwQDRAMEQwQDRAMEQwQDRAMEQwQDRApEA0QDRAMEQwQ
        DRAMEQwQDRAMESkQDBEMEA0QDRAMEQwQDRAMESkQDBEpEAwRDBANEA0QDBAqEAwRKRAMEQwQDRAM
        ESkQAAmgdDgQDBEpEA0QDBANEA0QDBEMEA0QDBEMEA0QDBEpEAwRDBANEA0QDBEMEA0QDBEMECkR
        DBANEAwRDBANEA0QDBANECkRDBApEQwQDRAMEQwQDRApEA0QKRANEA0QDBEMECkRAAmhdDcQDRAp
        EA4PDRAMEQwQDRAMEQwQDRAMEQwQDRApEA0QDRAMEA0QDRAMEQwQDRAMESgRDBEMEA0QDRAMEA0Q
        DRAMESkQDBEpEAwRDBANEAwRDBAqEAwRKRAMEQwQDRAMESkQAA0FEQwQDSYAZAJzOBANECkQDRAM
        EQwQDRAMEQwQDRAMEQwQDRANECkQDRAMEQwQDRAMEQwQDRAMEQwQKhAMEA0QDRAMEQwQDRAMEQwQ
        KREMECkRDBANEA0QDBANECkRDBApEQwQDRAMEQwQKhAACaB0NxEMECoQDBANEA0QDBEMEA0QDBEM
        EA0QDBEMECoQDBANEA0QDBEMEA0QDBEMEA0QKRANEAwRDBANEA0QDBANEA0QKRANECkQDRAMEQwQ
        DRAMESkQDRApEA0QDBEMEA0QKRAACaF0OBANECkQDRAMEQwQDRAMEQwQDRAMEQwQDRAMESkQDRAM
        EA0QDRAMEQwQDRAMEQwQKREMEA0QDRAMEA0QDRAMEQwQKREMECkRDBANEAwRDBANECkRDBApEQwQ
        DRAMEQwQKREACaF0NxANECkRDBANEAwRDBANEAwRDBANEAwRDBANECkQDRANEAwRDBANEAwRDBAN
        EAwRKRAMEQwQDRANEAwRDBANEAwRKRAMESkQDBEMEA0QDRAMECoQDBEpEAwRDBANEAwRKRAACaB0
        OBAMESkQDRAMEA0QDRAMEQwQDRAMEQwQDRAMESkQDBEMEA0QDRAMEQwQDRAMEQwQKREMEA0QDBEM
        EA0QDRAMEA0QKREMECkRDBANEAwRDBANECkQDRApEA0QDRAMEQwQKREACaF0NxANECkQDg8NEAwR
        DBANEAwRDBANEAwRDBANECkQDRANEAwQDRANEAwRDBANEAwRKBEMEQwQDRANEAwQDRANEAwRKRAM
        ESkQDBEMEA0QDBEMECoQDBEpEAwRDBANEAwRKRAADQURDBAN'
      # Will work on most LG TVs
      tv_living:
        friendly_name: "27"
        command_on: 'JgBsAgkACvF0NxANECoPDRANEA0PDRANEA4PDBANEA0QDBANECoPDRANEA0PDRANEA0PDRANEA0Q
        KRANEAwQDRANEA0PDRANEA4ODg8qEAwQDRApECoQDBANEA0QKRANEA0QKRApEA0QKRAAAfIFAAek
        dDcQDRApEA0QDRANDw0QDRANDw0QDRANEAwQDRApEA0QDRANDw0QDg8NDw0QDg8NDyoQDRAMEA0Q
        Dg8MEA4PDRANDw0QKhAMEAwRKRAqEAwQDRANECkQDRANDyoQKRANECkQAAmadDcQDRAqDw0QDRAN
        EAwQDRANEA0PDRANEAwQDRAqDw0QDRANDw0QDRANEAwQDRANECYTDRAMEA4PDRANDw0QDRANEAwQ
        KhAMEA0QKRAqEA0PDRANECkQDRANECkQKRANECoPAAmZdTgQDBAqEAwQDRANEAwQDRANEA0PDRAN
        EA0PDg8qEAwQDRANEAwQDRANEA0PDg8NECkQDRANDw0QDRANEAwQDg8NEAwQKhANDw0QKg8qEA0Q
        DBANECkQDRANECkQKg8NECoQAAmadDgPDRAqEAwQDRANEAwQDRANEAwQDg8NEA0PDRAqDw0QDRAN
        EAwQDRANEAwQDRANECkQDRANDw0QDRANDw0QDRANEAwQKhAMEA0QKg8qEA0PDRANECkQDRANECkQ
        Kg8NECoPAAmadDgQDBAqEAwQDRANEA0PDRANEA0PDRANEA0PDRAqEAwQDRANEAwQDRANEA0PDg8O
        DykQDRANEAwQDRANEAwQDRAODw0PKhANDw0QKhApEA0QDBANECoPDRANECkQKg8NECoQAA0FDw4P
        KhAMEA0QDRAMJgBsAgkACvF0NxANECoPDRANEA0PDRANEA4PDBANEA0QDBANECoPDRANEA0PDRAN
        EA0PDRANEA0QKRANEAwQDRANEA0PDRANEA4ODg8qEAwQDRApECoQDBANEA0QKRANEA0QKRApEA0Q
        KRAAAfIFAAekdDcQDRApEA0QDRANDw0QDRANDw0QDRANEAwQDRApEA0QDRANDw0QDg8NDw0QDg8N
        DyoQDRAMEA0QDg8MEA4PDRANDw0QKhAMEAwRKRAqEAwQDRANECkQDRANDyoQKRANECkQAAmadDcQ
        DRAqDw0QDRANEAwQDRANEA0PDRANEAwQDRAqDw0QDRANDw0QDRANEAwQDRANECYTDRAMEA4PDRAN
        Dw0QDRANEAwQKhAMEA0QKRAqEA0PDRANECkQDRANECkQKRANECoPAAmZdTgQDBAqEAwQDRANEAwQ
        DRANEA0PDRANEA0PDg8qEAwQDRANEAwQDRANEA0PDg8NECkQDRANDw0QDRANEAwQDg8NEAwQKhAN
        Dw0QKg8qEA0QDBANECkQDRANECkQKg8NECoQAAmadDgPDRAqEAwQDRANEAwQDRANEAwQDg8NEA0P
        DRAqDw0QDRANEAwQDRANEAwQDRANECkQDRANDw0QDRANDw0QDRANEAwQKhAMEA0QKg8qEA0PDRAN
        ECkQDRANECkQKg8NECoPAAmadDgQDBAqEAwQDRANEA0PDRANEA0PDRANEA0PDRAqEAwQDRANEAwQ
        DRANEA0PDg8ODykQDRANEAwQDRANEAwQDRAODw0PKhANDw0QKhApEA0QDBANECoPDRANECkQKg8N
        ECoQAA0FDw4PKhAMEA0QDRAMJgBsAgkACvF0NxANECoPDRANEA0PDRANEA4PDBANEA0QDBANECoP
        DRANEA0PDRANEA0PDRANEA0QKRANEAwQDRANEA0PDRANEA4ODg8qEAwQDRApECoQDBANEA0QKRAN
        EA0QKRApEA0QKRAAAfIFAAekdDcQDRApEA0QDRANDw0QDRANDw0QDRANEAwQDRApEA0QDRANDw0Q
        Dg8NDw0QDg8NDyoQDRAMEA0QDg8MEA4PDRANDw0QKhAMEAwRKRAqEAwQDRANECkQDRANDyoQKRAN
        ECkQAAmadDcQDRAqDw0QDRANEAwQDRANEA0PDRANEAwQDRAqDw0QDRANDw0QDRANEAwQDRANECYT
        DRAMEA4PDRANDw0QDRANEAwQKhAMEA0QKRAqEA0PDRANECkQDRANECkQKRANECoPAAmZdTgQDBAq
        EAwQDRANEAwQDRANEA0PDRANEA0PDg8qEAwQDRANEAwQDRANEA0PDg8NECkQDRANDw0QDRANEAwQ
        Dg8NEAwQKhANDw0QKg8qEA0QDBANECkQDRANECkQKg8NECoQAAmadDgPDRAqEAwQDRANEAwQDRAN
        EAwQDg8NEA0PDRAqDw0QDRANEAwQDRANEAwQDRANECkQDRANDw0QDRANDw0QDRANEAwQKhAMEA0Q
        Kg8qEA0PDRANECkQDRANECkQKg8NECoPAAmadDgQDBAqEAwQDRANEA0PDRANEA0PDRANEA0PDRAq
        EAwQDRANEAwQDRANEA0PDg8ODykQDRANEAwQDRANEAwQDRAODw0PKhANDw0QKhApEA0QDBANECoP
        DRANECkQKg8NECoQAA0FDw4PKhAMEA0QDRAM'
      
      tv_living:
        friendly_name: "26"
        command_on: 'JgCEAxANEAwQDRANEAwQDRANEAwQDRAnEg0QDRANEAwQDRANEAwQDRANECkQDRAMEA0QDRANEAwQ
        DRANEAwQDRApEA0QKRAqEA0PCxINEA0QKRANECkQKRANECkQAAmadDcRDBAmFAwQDRANEAwQDRAN
        EAwQDRANEAwRDBAqEAwQDRANEAwQDRANEAwQDRANECkQDRANEAwQDRANEAwQDRANEAsRDRAoEQ0Q
        KhApEA0QDBAODw0QKRANECkQKhAMECoQAAmZdDYSDBAqEAwQDRANEA0QDBANEA0QDBANEA0QDBAq
        EAwQDRANEAwRDBANEA0QDBANECkQDRANEAwQDRANEAwQCxINEA0QDBAqEAwQKhApEA0QDBANEA0Q
        KRANECkQKhAMECoQAAmadDgQDBAqEAwQDRANEAwQDRANEA0QDBANEA0QDBAqEAwQDRAMEQwQDRAN
        EAwRDBANECkQDRANEAwQDRANEAwQDRANEAwQDRAqEAwQKREpEA0QDBANEA0QKRANECkQKhAMECoQ
        AAE7CgAChwgAAo0IAAKNC5h0OBAMECoQDBEMEA0QDRAMEA0QDRAMEA0QDRAMECoQDBEMEA0QDRAM
        EA0QDRAMEA0QKRANEA0QDBANEA0QDRAMEA0QDRAMECoQDBAqECkQCxIMEA0QDRApEA0QKRAqEAwQ
        HR0AAngKAAKMCQACjAkAAe5zKx0NDyoQDRAMEA0QDRAMEA0QDRAMEA0QDRAMESkQDRAMEA0QDRAM
        EA0QCxIMEA0QKRANEA0QDBANEA0QDRAMEA0QDRAMECoQDBAqECkQDRAODwwQDRApEA0QKRAqEAwQ
        KhAAASUFAAKQCAACjAoAAo0Gr3Q3EA0QKhAMEA0QDRAMEA0QDRAMEA0QDRAMEA0QKg8NEA0QDQ8N
        EA0QDRANDw0QDg8pEA0QDBANEA0QDQ8NEA0QDQ8NEA0QKRANECkQKhANDw4PDRAODioQDRApECkQ
        DRApEAACbAoABRwFAAKQBQACkAsAAowJAAKJCgACjQkAAooJAAKFCgAChwoAAoQKAAKLCgACjAoA
        AowJAAKMCgACiwoAAo0JAAKNCQACjAoAAosKAAKLCgACjAoAAowJAAKMCgACjAoAAowJAAKNCgAC
        iwoAAowKAAKLCgACgwkAAowKAAKMCgACiwoAAowJAAKMCgACjAkAAo0KAAKLCQANBQAAAAAmAIQD
        EA0QDBANEA0QDBANEA0QDBANECcSDRANEA0QDBANEA0QDBANEA0QKRANEAwQDRANEA0QDBANEA0Q
        DBANECkQDRApECoQDQ8LEg0QDRApEA0QKRApEA0QKRAACZp0NxEMECYUDBANEA0QDBANEA0QDBAN
        EA0QDBEMECoQDBANEA0QDBANEA0QDBANEA0QKRANEA0QDBANEA0QDBANEA0QCxENECgRDRAqECkQ
        DRAMEA4PDRApEA0QKRAqEAwQKhAACZl0NhIMECoQDBANEA0QDRAMEA0QDRAMEA0QDRAMECoQDBAN
        EA0QDBEMEA0QDRAMEA0QKRANEA0QDBANEA0QDBALEg0QDRAMECoQDBAqECkQDRAMEA0QDRApEA0Q
        KRAqEAwQKhAACZp0OBAMECoQDBANEA0QDBANEA0QDRAMEA0QDRAMECoQDBANEAwRDBANEA0QDBEM
        EA0QKRANEA0QDBANEA0QDBANEA0QDBANECoQDBApESkQDRAMEA0QDRApEA0QKRAqEAwQKhAAATsK
        AAKHCAACjQgAAo0LmHQ4EAwQKhAMEQwQDRANEAwQDRANEAwQDRANEAwQKhAMEQwQDRANEAwQDRAN
        EAwQDRApEA0QDRAMEA0QDRANEAwQDRANEAwQKhAMECoQKRALEgwQDRANECkQDRApECoQDBAdHQAC
        eAoAAowJAAKMCQAB7nMrHQ0PKhANEAwQDRANEAwQDRANEAwQDRANEAwRKRANEAwQDRANEAwQDRAL
        EgwQDRApEA0QDRAMEA0QDRANEAwQDRANEAwQKhAMECoQKRANEA4PDBANECkQDRApECoQDBAqEAAB
        JQUAApAIAAKMCgACjQavdDcQDRAqEAwQDRANEAwQDRANEAwQDRANEAwQDRAqDw0QDRANDw0QDRAN
        EA0PDRAODykQDRAMEA0QDRANDw0QDRANDw0QDRApEA0QKRAqEA0PDg8NEA4OKhANECkQKRANECkQ
        AAJsCgAFHAUAApAFAAKQCwACjAkAAokKAAKNCQACigkAAoUKAAKHCgAChAoAAosKAAKMCgACjAkA
        AowKAAKLCgACjQkAAo0JAAKMCgACiwoAAosKAAKMCgACjAkAAowKAAKMCgACjAkAAo0KAAKLCgAC
        jAoAAosKAAKDCQACjAoAAowKAAKLCgACjAkAAowKAAKMCQACjQoAAosJAA0FAAAAACYAhAMQDRAM
        EA0QDRAMEA0QDRAMEA0QJxINEA0QDRAMEA0QDRAMEA0QDRApEA0QDBANEA0QDRAMEA0QDRAMEA0Q
        KRANECkQKhANDwsSDRANECkQDRApECkQDRApEAAJmnQ3EQwQJhQMEA0QDRAMEA0QDRAMEA0QDRAM
        EQwQKhAMEA0QDRAMEA0QDRAMEA0QDRApEA0QDRAMEA0QDRAMEA0QDRALEQ0QKBENECoQKRANEAwQ
        Dg8NECkQDRApECoQDBAqEAAJmXQ2EgwQKhAMEA0QDRANEAwQDRANEAwQDRANEAwQKhAMEA0QDRAM
        EQwQDRANEAwQDRApEA0QDRAMEA0QDRAMEAsSDRANEAwQKhAMECoQKRANEAwQDRANECkQDRApECoQ
        DBAqEAAJmnQ4EAwQKhAMEA0QDRAMEA0QDRANEAwQDRANEAwQKhAMEA0QDBEMEA0QDRAMEQwQDRAp
        EA0QDRAMEA0QDRAMEA0QDRAMEA0QKhAMECkRKRANEAwQDRANECkQDRApECoQDBAqEAABOwoAAocI
        AAKNCAACjQuYdDgQDBAqEAwRDBANEA0QDBANEA0QDBANEA0QDBAqEAwRDBANEA0QDBANEA0QDBAN
        ECkQDRANEAwQDRANEA0QDBANEA0QDBAqEAwQKhApEAsSDBANEA0QKRANECkQKhAMEB0dAAJ4CgAC
        jAkAAowJAAHucysdDQ8qEA0QDBANEA0QDBANEA0QDBANEA0QDBEpEA0QDBANEA0QDBANEAsSDBAN
        ECkQDRANEAwQDRANEA0QDBANEA0QDBAqEAwQKhApEA0QDg8MEA0QKRANECkQKhAMECoQAAElBQAC
        kAgAAowKAAKNBq90NxANECoQDBANEA0QDBANEA0QDBANEA0QDBANECoPDRANEA0PDRANEA0QDQ8N
        EA4PKRANEAwQDRANEA0PDRANEA0PDRANECkQDRApECoQDQ8ODw0QDg4qEA0QKRApEA0QKRAAAmwK
        AAUcBQACkAUAApALAAKMCQACiQoAAo0JAAKKCQAChQoAAocKAAKECgACiwoAAowKAAKMCQACjAoA
        AosKAAKNCQACjQkAAowKAAKLCgACiwoAAowKAAKMCQACjAoAAowKAAKMCQACjQoAAosKAAKMCgAC
        iwoAAoMJAAKMCgACjAoAAosKAAKMCQACjAoAAowJAAKNCgACiwkADQUAAAAA'
      tv_living:
        friendly_name: "25"
        command_on: 'JgDMAHQ3EQwQKBIMEA0QDRAMEA0QDRANDw0QDRANDw0QKhAMEA0QDRAMEA0QDRANDw0QDRApEA0Q
        DRAMEA0QDRAMEA0QDRAMEA0QKg8NECoQDBAqECkQDRAMECoQDQ8qEA0PKhANEAAJmnQ3EA0QKhAM
        EA0QDg8NDw4PDg8NDw4PDg8NDw4PKhAMEA4PDRANDw0QDg8NDw0QDg8pEA0QDQ8ODw4PDg4ODwwR
        Dg8MEA4PKRANECcSDRAqDyoQDRAMECoQDBAqEAwQJhQNDwANBQAAAAAAAAAAAAAAACYAzAB0NxEM
        ECgSDBANEA0QDBANEA0QDQ8NEA0QDQ8NECoQDBANEA0QDBANEA0QDQ8NEA0QKRANEA0QDBANEA0Q
        DBANEA0QDBANECoPDRAqEAwQKhApEA0QDBAqEA0PKhANDyoQDRAACZp0NxANECoQDBANEA4PDQ8O
        Dw4PDQ8ODw4PDQ8ODyoQDBAODw0QDQ8NEA4PDQ8NEA4PKRANEA0PDg8ODw4ODg8MEQ4PDBAODykQ
        DRAnEg0QKg8qEA0QDBAqEAwQKhAMECYUDQ8ADQUAAAAAAAAAAAAAAAAmAMwAdDcRDBAoEgwQDRAN
        EAwQDRANEA0PDRANEA0PDRAqEAwQDRANEAwQDRANEA0PDRANECkQDRANEAwQDRANEAwQDRANEAwQ
        DRAqDw0QKhAMECoQKRANEAwQKhANDyoQDQ8qEA0QAAmadDcQDRAqEAwQDRAODw0PDg8ODw0PDg8O
        Dw0PDg8qEAwQDg8NEA0PDRAODw0PDRAODykQDRANDw4PDg8ODg4PDBEODwwQDg8pEA0QJxINECoP
        KhANEAwQKhAMECoQDBAmFA0PAA0FAAAAAAAAAAAAAAAA'
      tv_living:
        friendly_name: "12"
        command_on: 'JgDQAHM4EA0QKRANEAwQDRANEA0PDRAODw0PDg8ODw0QKRANEA0PDRANEA0PDg8NEA0PDRAfGg0Q
        DRANEAwQDRANEAwQDRAqDw0QDRANDw0QKg8NEA0QKRAODw0QDBANECkQDRAqDwABxQYAB9V2NxAN
        ECkQDRANEAwQDRANEAwQDRANEA0PDRANECkQDRANEAwQDRANEAwQDRANEAwQKhALEQ0QDRANEAwQ
        DRANEAwQKhAMEA0QDRAMECoQDRAMECoQDBANEA0QDBAqEAwQKhAADQUAAAAAAAAAACYA0ABzOBAN
        ECkQDRAMEA0QDRANDw0QDg8NDw4PDg8NECkQDRANDw0QDRANDw4PDRANDw0QHxoNEA0QDRAMEA0Q
        DRAMEA0QKg8NEA0QDQ8NECoPDRANECkQDg8NEAwQDRApEA0QKg8AAcUGAAfVdjcQDRApEA0QDRAM
        EA0QDRAMEA0QDRANDw0QDRApEA0QDRAMEA0QDRAMEA0QDRAMECoQCxENEA0QDRAMEA0QDRAMECoQ
        DBANEA0QDBAqEA0QDBAqEAwQDRANEAwQKhAMECoQAA0FAAAAAAAAAAAmANAAczgQDRApEA0QDBAN
        EA0QDQ8NEA4PDQ8ODw4PDRApEA0QDQ8NEA0QDQ8ODw0QDQ8NEB8aDRANEA0QDBANEA0QDBANECoP
        DRANEA0PDRAqDw0QDRApEA4PDRAMEA0QKRANECoPAAHFBgAH1XY3EA0QKRANEA0QDBANEA0QDBAN
        EA0QDQ8NEA0QKRANEA0QDBANEA0QDBANEA0QDBAqEAsRDRANEA0QDBANEA0QDBAqEAwQDRANEAwQ
        KhANEAwQKhAMEA0QDRAMECoQDBAqEAANBQAAAAAAAAAA'
        
