homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 51.5388
  longitude: -0.1520
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 30
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London


# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  platform: yr

# Text to speech
tts:
  platform: google

media_player livingRoom:
  - platform: kodi
    host: 192.168.0.4
    port: 18080
    username: kodi
    password: arse

media_player cast:
  - platform: cast

light:
  platform: limitlessled
  bridges:
    - host: 192.168.0.16
      groups:
      - number: 1
        name: Bed Room
        type: rgbw
      - number: 2
        type: rgbw
        name: Living Room 1
      - number: 3
        type: rgbw
        name: Living Room 2
      - number: 4
        type: rgbw 
        name: 4


emulated_hue:

switch:
  - platform: broadlink
    host: 192.168.0.19
    mac: 34:ea:34:e7:f9:68
    friendly_name: ultraremote
